python main.py --config configs/caltech101.yaml --shot 8
python main.py --config configs/dtd.yaml --shot 8
python main.py --config configs/eurosat.yaml --shot 8
python main.py --config configs/fgvc.yaml --shot 8
python main.py --config configs/food101.yaml --shot 8
python main.py --config configs/oxford_flowers.yaml --shot 8
python main.py --config configs/oxford_pets.yaml --shot 8
python main.py --config configs/stanford_cars.yaml --shot 8
python main.py --config configs/sun397.yaml --shot 8
python main.py --config configs/ucf101.yaml --shot 8